name: pisni
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: 4.9.0
  provider: ^6.1.2

dev_dependencies:
  json_serializable: 6.9.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categories/
    - assets/authors/
