name: pisni
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  intl: any
  json_annotation: 4.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  vector_graphics_compiler: ^1.1.16

dev_dependencies:
  json_serializable: 6.9.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  drift_dev: ^2.26.1
  test: ^1.25.15

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/songs/
    - assets/icons/
